<?php $products = $this->PromoListable();

 //eğer bunu açarsan tüm kullancagın elemanları gorursun 
 //echo '<pre>'; print_r($products);

/*
kullacağın degerler
            [RuleId] => 119
            [Name] => WEB - Platinium Paket
            [A_TopBannerDescription] =>
            [A_promoType] => 0
            [A_promoMinPrice] =>
            [A_Type] => 0
            [A_MinPrice] =>
            [A_UseDiscountAmount] => 0
            [A_ShowOrigPrice] => 0
            [A_FreeShipping] => global
            [A_TopBannerImg] =>
            [A_TopBannerAlt] =>
            [A_TopBannerHoverText] =>
            [A_TopBannerLink] =>
            [A_TopBannerGiftImages] => 0
            [A_AfterNameBannerDescription] =>
            [A_AfterNameBannerImg] =>
            [A_AfterNameBanneAlt] =>
            [A_AfterNameBannerHoverText] =>
            [A_AfterNameBannerLink] =>
            [A_LabelImg] =>
            [A_AfterNameBannerGiftImages] => 0
            [A_LabelAlt] =>

ORnek kullanım  echo $product['A_LabelImg'];

 <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" class="product-image"></a>

 * */


?>
<article>	
<?php foreach ($products as $product): ?>

<section>
<a href="<?php echo $product['A_AfterNameBannerLink']; ?>" title="<?php    echo $product['Name']; ?>">
<img class="" src="/media/ampromo/<?php echo $product['A_AfterNameBannerImg']; ?>" alt="<?php    echo $product['Name']; ?>" >
</a>

<h3><?php    echo $product['Name']; ?></h3>
<?php    echo $product['A_AfterNameBannerDescription']; ?>

<a class="button" href="<?php echo $product['A_AfterNameBannerLink']; ?>" title="<?php    echo $product['Name']; ?>"> KEŞFET </a>
</section>
   
<?php endforeach; ?>
</article>






<style>
*, *:before, *:after {box-sizing:  border-box !important;}


article {
 -moz-column-width: 20em;
 -webkit-column-width: 20em;
 -moz-column-gap: 1em;
 -webkit-column-gap: 1em; 
  
}

section {
 display: inline-block;
 margin:  0.5rem;
 padding:  1rem;
 width:  100%; 
 background:  #efefef;
}


p {
 margin:  1rem 0; 
}


</style>